using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace BMapSharp.VirtoolsTypes {

    #region Structures

    // NOTE: Structures defined in there is only served for marshaling.
    // You should not use them in hash set or anything else,
    // because they do not have proper hash function and compare function.
    // You should use the managed type generated by them instead.

    [StructLayout(LayoutKind.Sequential, Pack = 4, CharSet = CharSet.Ansi)]
    public struct VxVector2 {
        [MarshalAs(UnmanagedType.R4)]
        public float X, Y;

        public VxVector2(float _x = 0.0f, float _y = 0.0f) {
            X = _x; Y = _y;
        }
        public VxVector2(Vector2 vec) {
            FromManaged(vec);
        }

        public void FromManaged(Vector2 vec) {
            X = vec.X; Y = vec.Y;
        }
        public Vector2 ToManaged() {
            return new Vector2(X, Y);
        }
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4, CharSet = CharSet.Ansi)]
    public struct VxVector3 {
        [MarshalAs(UnmanagedType.R4)]
        public float X, Y, Z;

        public VxVector3(float _x = 0.0f, float _y = 0.0f, float _z = 0.0f) {
            X = _x; Y = _y; Z = _z;
        }
        public VxVector3(Vector3 vec) {
            FromManaged(vec);
        }

        public void FromManaged(Vector3 vec) {
            X = vec.X; Y = vec.Y; Z = vec.Z;
        }
        public Vector3 ToManaged() {
            return new Vector3(X, Y, Z);
        }
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4, CharSet = CharSet.Ansi)]
    public struct VxColor {
        [MarshalAs(UnmanagedType.R4)]
        public float R, G, B, A;

        public VxColor(float _r, float _g, float _b, float _a) {
            A = _a; R = _r; G = _g; B = _b;
            Regulate();
        }
        public VxColor(Vector4 col) {
            FromManagedRGBA(col);
        }
        public VxColor(Vector3 col) {
            FromManagedRGB(col);
        }
        public VxColor(uint val) {
            FromDword(val);
        }

        public void FromManagedRGBA(Vector4 col) {
            R = col.X;  G = col.Y; B = col.Z; A = col.W;
            Regulate();
        }
        public Vector4 ToManagedRGBA() {
            return new Vector4(R, G, B, A);
        }
        public void FromManagedRGB(Vector3 col) {
            R = col.X; G = col.Y; B = col.Z; A = 1.0f;
            Regulate();
        }
        public Vector3 ToManagedRGB() {
            return new Vector3(R, G, B);
        }
        public void FromDword(uint val) {
            B = (val & 0xFFu) / 255.0f;
            val >>= 8;
            G = (val & 0xFFu) / 255.0f;
            val >>= 8;
            R = (val & 0xFFu) / 255.0f;
            val >>= 8;
            A = (val & 0xFFu) / 255.0f;
        }
        public uint ToDword() {
            // regulate self first
            Regulate();
            // build result
            uint val = 0u;
            val |= (uint)(A * 255.0f);
            val <<= 8;
            val |= (uint)(R * 255.0f);
            val <<= 8;
            val |= (uint)(G * 255.0f);
            val <<= 8;
            val |= (uint)(B * 255.0f);
            return val;
        }
        
        public static float ClampFactor(float factor) {
            return System.Math.Clamp(factor, 0.0f, 1.0f);
        }
        public void Regulate() {
            A = ClampFactor(A);
            R = ClampFactor(R);
            G = ClampFactor(G);
            B = ClampFactor(B);
        }
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4, CharSet = CharSet.Ansi)]
    public struct VxMatrix {
        [MarshalAs(UnmanagedType.R4)]
        public float M11, M12, M13, M14;
        [MarshalAs(UnmanagedType.R4)]
        public float M21, M22, M23, M24;
        [MarshalAs(UnmanagedType.R4)]
        public float M31, M32, M33, M34;
        [MarshalAs(UnmanagedType.R4)]
        public float M41, M42, M43, M44;

        public VxMatrix(float m11 = 1.0f, float m12 = 0.0f, float m13 = 0.0f, float m14 = 0.0f,
                        float m21 = 0.0f, float m22 = 1.0f, float m23 = 0.0f, float m24 = 0.0f,
                        float m31 = 0.0f, float m32 = 0.0f, float m33 = 1.0f, float m34 = 0.0f,
                        float m41 = 0.0f, float m42 = 0.0f, float m43 = 0.0f, float m44 = 1.0f) {
            M11 = m11; M12 = m12; M13 = m13; M14 = m14;
            M21 = m21; M22 = m22; M23 = m23; M24 = m24;
            M31 = m31; M32 = m32; M33 = m33; M34 = m34;
            M41 = m41; M42 = m42; M43 = m43; M44 = m44;
        }
        public void Reset() {
            M11 = 1.0f; M12 = 0.0f; M13 = 0.0f; M14 = 0.0f;
            M21 = 0.0f; M22 = 1.0f; M23 = 0.0f; M24 = 0.0f;
            M31 = 0.0f; M32 = 0.0f; M33 = 1.0f; M34 = 0.0f;
            M41 = 0.0f; M42 = 0.0f; M43 = 0.0f; M44 = 1.0f;
        }
        public void FromManaged(Matrix4x4 mat) {
            M11 = mat.M11; M12 = mat.M12; M13 = mat.M13; M14 = mat.M14;
            M21 = mat.M21; M22 = mat.M22; M23 = mat.M23; M24 = mat.M24;
            M31 = mat.M31; M32 = mat.M32; M33 = mat.M33; M34 = mat.M34;
            M41 = mat.M41; M42 = mat.M42; M43 = mat.M43; M44 = mat.M44;
        }
        public Matrix4x4 ToManaged() {
            return new Matrix4x4(
                M11, M12, M13, M14,
                M21, M22, M23, M24,
                M31, M32, M33, M34,
                M41, M42, M43, M44
            );
        }
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4, CharSet = CharSet.Ansi)]
    public struct CKFaceIndices {
        [MarshalAs(UnmanagedType.U4)]
        public uint I1, I2, I3;

        public CKFaceIndices(uint i1 = 0u, uint i2 = 0u, uint i3 = 0u) {
            I1 = i1;
            I2 = i2;
            I3 = i3;
        }
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4, CharSet = CharSet.Ansi)]
    public struct CKShortFaceIndices {
        [MarshalAs(UnmanagedType.U2)]
        public ushort I1, I2, I3;

        public CKShortFaceIndices(ushort i1 = 0, ushort i2 = 0, ushort i3 = 0) {
            I1 = i1;
            I2 = i2;
            I3 = i3;
        }
    }

    #endregion

    #region Enums

    /// <summary>
    /// Specify the way textures or sprites will be saved
    /// </summary>
    public enum CK_TEXTURE_SAVEOPTIONS : uint {
        /// <summary>
        /// Save raw data inside file. The bitmap is saved in a raw 32 bit per pixel format.
        /// </summary>
        CKTEXTURE_RAWDATA = 0,
        /// <summary>
        /// Store only the file name for the texture. The bitmap file must be present in the bitmap pathswhen loading the composition.
        /// </summary>
        CKTEXTURE_EXTERNAL = 1,
        /// <summary>
        /// Save using format specified. The bitmap data will be converted to thespecified format by the correspondant bitmap plugin and saved inside file.
        /// </summary>
        CKTEXTURE_IMAGEFORMAT = 2,
        /// <summary>
        /// Use Global settings, that is the settings given with CKContext::SetGlobalImagesSaveOptions. (Not valid when using CKContext::SetImagesSaveOptions).
        /// </summary>
        CKTEXTURE_USEGLOBAL = 3,
        /// <summary>
        /// Insert original image file inside CMO file. The bitmap file thatwas used originally for the texture or sprite will be append tothe composition file and extracted when the file is loaded.
        /// </summary>
        CKTEXTURE_INCLUDEORIGINALFILE = 4,
    };

    /// <summary>
    /// Pixel format types.
    /// </summary>
    public enum VX_PIXELFORMAT : uint {
        /// <summary>
        /// Unknown pixel format
        /// </summary>
        UNKNOWN_PF = 0,
        /// <summary>
        /// 32-bit ARGB pixel format with alpha
        /// </summary>
        _32_ARGB8888 = 1,
        /// <summary>
        /// 32-bit RGB pixel format without alpha
        /// </summary>
        _32_RGB888 = 2,
        /// <summary>
        /// 24-bit RGB pixel format
        /// </summary>
        _24_RGB888 = 3,
        /// <summary>
        /// 16-bit RGB pixel format
        /// </summary>
        _16_RGB565 = 4,
        /// <summary>
        /// 16-bit RGB pixel format (5 bits per color)
        /// </summary>
        _16_RGB555 = 5,
        /// <summary>
        /// 16-bit ARGB pixel format (5 bits per color + 1 bit for alpha)
        /// </summary>
        _16_ARGB1555 = 6,
        /// <summary>
        /// 16-bit ARGB pixel format (4 bits per color)
        /// </summary>
        _16_ARGB4444 = 7,
        /// <summary>
        /// 8-bit  RGB pixel format
        /// </summary>
        _8_RGB332 = 8,
        /// <summary>
        /// 8-bit  ARGB pixel format
        /// </summary>
        _8_ARGB2222 = 9,
        /// <summary>
        /// 32-bit ABGR pixel format
        /// </summary>
        _32_ABGR8888 = 10,
        /// <summary>
        /// 32-bit RGBA pixel format
        /// </summary>
        _32_RGBA8888 = 11,
        /// <summary>
        /// 32-bit BGRA pixel format
        /// </summary>
        _32_BGRA8888 = 12,
        /// <summary>
        /// 32-bit BGR pixel format
        /// </summary>
        _32_BGR888 = 13,
        /// <summary>
        /// 24-bit BGR pixel format
        /// </summary>
        _24_BGR888 = 14,
        /// <summary>
        /// 16-bit BGR pixel format
        /// </summary>
        _16_BGR565 = 15,
        /// <summary>
        /// 16-bit BGR pixel format (5 bits per color)
        /// </summary>
        _16_BGR555 = 16,
        /// <summary>
        /// 16-bit ABGR pixel format (5 bits per color + 1 bit for alpha)
        /// </summary>
        _16_ABGR1555 = 17,
        /// <summary>
        /// 16-bit ABGR pixel format (4 bits per color)
        /// </summary>
        _16_ABGR4444 = 18,
        /// <summary>
        /// S3/DirectX Texture Compression 1
        /// </summary>
        _DXT1 = 19,
        /// <summary>
        /// S3/DirectX Texture Compression 2
        /// </summary>
        _DXT2 = 20,
        /// <summary>
        /// S3/DirectX Texture Compression 3
        /// </summary>
        _DXT3 = 21,
        /// <summary>
        /// S3/DirectX Texture Compression 4
        /// </summary>
        _DXT4 = 22,
        /// <summary>
        /// S3/DirectX Texture Compression 5
        /// </summary>
        _DXT5 = 23,
        /// <summary>
        /// 16-bit Bump Map format format (8 bits per color)
        /// </summary>
        _16_V8U8 = 24,
        /// <summary>
        /// 32-bit Bump Map format format (16 bits per color)
        /// </summary>
        _32_V16U16 = 25,
        /// <summary>
        /// 16-bit Bump Map format format with luminance
        /// </summary>
        _16_L6V5U5 = 26,
        /// <summary>
        /// 32-bit Bump Map format format with luminance
        /// </summary>
        _32_X8L8V8U8 = 27,
        /// <summary>
        /// 8 bits indexed CLUT (ABGR)
        /// </summary>
        _8_ABGR8888_CLUT = 28,
        /// <summary>
        /// 8 bits indexed CLUT (ARGB)
        /// </summary>
        _8_ARGB8888_CLUT = 29,
        /// <summary>
        /// 4 bits indexed CLUT (ABGR)
        /// </summary>
        _4_ABGR8888_CLUT = 30,
        /// <summary>
        /// 4 bits indexed CLUT (ARGB)
        /// </summary>
        _4_ARGB8888_CLUT = 31,
    };

    /// <summary>
    /// Light type.
    /// </summary>
    public enum VXLIGHT_TYPE : uint {
        /// <summary>
        /// The Light is a point of light
        /// </summary>
        VX_LIGHTPOINT = 1U,
        /// <summary>
        /// The light is a spotlight
        /// </summary>
        VX_LIGHTSPOT = 2U,
        /// <summary>
        /// The light is directional light : Lights comes from an infinite point so only direction of light can be given
        /// </summary>
        VX_LIGHTDIREC = 3U,
        // /// <summary>
        // /// Obsolete, do not use
        // /// </summary>
        // VX_LIGHTPARA = 4U,
    };

    /// <summary>
    /// Blend Mode Flags
    /// </summary>
    public enum VXTEXTURE_BLENDMODE : uint {
        /// <summary>
        /// Texture replace any material information
        /// </summary>
        VXTEXTUREBLEND_DECAL = 1U,
        /// <summary>
        /// Texture and material are combine. Alpha information of the texture replace material alpha component.
        /// </summary>
        VXTEXTUREBLEND_MODULATE = 2U,
        /// <summary>
        /// Alpha information in the texture specify how material and texture are combined. Alpha information of the texture replace material alpha component.
        /// </summary>
        VXTEXTUREBLEND_DECALALPHA = 3U,
        /// <summary>
        /// Alpha information in the texture specify how material and texture are combined
        /// </summary>
        VXTEXTUREBLEND_MODULATEALPHA = 4U,
        VXTEXTUREBLEND_DECALMASK = 5U,
        VXTEXTUREBLEND_MODULATEMASK = 6U,
        /// <summary>
        /// Equivalent to DECAL
        /// </summary>
        VXTEXTUREBLEND_COPY = 7U,
        VXTEXTUREBLEND_ADD = 8U,
        /// <summary>
        /// Perform a Dot Product 3 between texture (normal map)and a referential vector given in VXRENDERSTATE_TEXTUREFACTOR.
        /// </summary>
        VXTEXTUREBLEND_DOTPRODUCT3 = 9U,
        VXTEXTUREBLEND_MAX = 10U,
        // VXTEXTUREBLEND_MASK = 0xFU,
    };

    /// <summary>
    /// Filter Mode Options
    /// </summary>
    [Flags]
    public enum VXTEXTURE_FILTERMODE : uint {
        /// <summary>
        /// No Filter
        /// </summary>
        VXTEXTUREFILTER_NEAREST = 1U,
        /// <summary>
        /// Bilinear Interpolation
        /// </summary>
        VXTEXTUREFILTER_LINEAR = 2U,
        /// <summary>
        /// Mip mapping
        /// </summary>
        VXTEXTUREFILTER_MIPNEAREST = 3U,
        /// <summary>
        /// Mip Mapping with Bilinear interpolation
        /// </summary>
        VXTEXTUREFILTER_MIPLINEAR = 4U,
        /// <summary>
        /// Mip Mapping with Bilinear interpolation between mipmap levels.
        /// </summary>
        VXTEXTUREFILTER_LINEARMIPNEAREST = 5U,
        /// <summary>
        /// Trilinear Filtering
        /// </summary>
        VXTEXTUREFILTER_LINEARMIPLINEAR = 6U,
        /// <summary>
        /// Anisotropic filtering
        /// </summary>
        VXTEXTUREFILTER_ANISOTROPIC = 7U,
        // VXTEXTUREFILTER_MASK = 0xFU,
    };

    /// <summary>
    /// Texture addressing modes.
    /// </summary>
    public enum VXTEXTURE_ADDRESSMODE : uint {
        /// <summary>
        /// Default mesh wrap mode is used (see CKMesh::SetWrapMode)
        /// </summary>
        VXTEXTURE_ADDRESSWRAP = 1U,
        /// <summary>
        /// Texture coordinates outside the range [0..1] are flipped evenly.
        /// </summary>
        VXTEXTURE_ADDRESSMIRROR = 2U,
        /// <summary>
        /// Texture coordinates greater than 1.0 are set to 1.0, and values less than 0.0 are set to 0.0.
        /// </summary>
        VXTEXTURE_ADDRESSCLAMP = 3U,
        /// <summary>
        /// When texture coordinates are greater than 1.0 or less than 0.0  texture is set to a color defined in CKMaterial::SetTextureBorderColor.
        /// </summary>
        VXTEXTURE_ADDRESSBORDER = 4U,
        /// <summary>
        /// 
        /// </summary>
        VXTEXTURE_ADDRESSMIRRORONCE = 5U,
        /// <summary>
        /// mask for all values
        /// </summary>
        // VXTEXTURE_ADDRESSMASK = 0x7U,
    }

    /// <summary>
    /// Blending Mode options
    /// </summary>
    public enum VXBLEND_MODE : uint {
        /// <summary>
        /// Blend factor is (0, 0, 0, 0).
        /// </summary>
        VXBLEND_ZERO = 1U,
        /// <summary>
        /// Blend factor is (1, 1, 1, 1).
        /// </summary>
        VXBLEND_ONE = 2U,
        /// <summary>
        /// Blend factor is (Rs, Gs, Bs, As).
        /// </summary>
        VXBLEND_SRCCOLOR = 3U,
        /// <summary>
        /// Blend factor is (1-Rs, 1-Gs, 1-Bs, 1-As).
        /// </summary>
        VXBLEND_INVSRCCOLOR = 4U,
        /// <summary>
        /// Blend factor is (As, As, As, As).
        /// </summary>
        VXBLEND_SRCALPHA = 5U,
        /// <summary>
        /// Blend factor is (1-As, 1-As, 1-As, 1-As).
        /// </summary>
        VXBLEND_INVSRCALPHA = 6U,
        /// <summary>
        /// Blend factor is (Ad, Ad, Ad, Ad).
        /// </summary>
        VXBLEND_DESTALPHA = 7U,
        /// <summary>
        /// Blend factor is (1-Ad, 1-Ad, 1-Ad, 1-Ad).
        /// </summary>
        VXBLEND_INVDESTALPHA = 8U,
        /// <summary>
        /// Blend factor is (Rd, Gd, Bd, Ad).
        /// </summary>
        VXBLEND_DESTCOLOR = 9U,
        /// <summary>
        /// Blend factor is (1-Rd, 1-Gd, 1-Bd, 1-Ad).
        /// </summary>
        VXBLEND_INVDESTCOLOR = 10U,
        /// <summary>
        /// Blend factor is (f, f, f, 1); f = min(As, 1-Ad).
        /// </summary>
        VXBLEND_SRCALPHASAT = 11U,
        // /// <summary>
        // /// Source blend factor is (As, As, As, As) and destination blend factor is (1-As, 1-As, 1-As, 1-As)
        // /// </summary>
        // VXBLEND_BOTHSRCALPHA = 12U,
        // /// <summary>
        // /// Source blend factor is (1-As, 1-As, 1-As, 1-As) and destination blend factor is (As, As, As, As)
        // /// </summary>
        // VXBLEND_BOTHINVSRCALPHA = 13U,
        // /// <summary>
        // /// Source blend factor is (1-As, 1-As, 1-As, 1-As) and destination blend factor is (As, As, As, As)
        // /// </summary>
        // VXBLEND_MASK = 0xFU,
    }

    /// <summary>
    /// Fill Mode Options
    /// </summary>
    public enum VXFILL_MODE : uint {
        /// <summary>
        /// Vertices rendering
        /// </summary>
        VXFILL_POINT = 1U,
        /// <summary>
        /// Edges rendering
        /// </summary>
        VXFILL_WIREFRAME = 2U,
        /// <summary>
        /// Face rendering
        /// </summary>
        VXFILL_SOLID = 3U,
        // VXFILL_MASK = 3U,
    }

    /// <summary>
    /// Shade Mode Options
    /// </summary>
    public enum VXSHADE_MODE : uint {
        /// <summary>
        /// Flat Shading
        /// </summary>
        VXSHADE_FLAT = 1U,
        /// <summary>
        /// Gouraud Shading
        /// </summary>
        VXSHADE_GOURAUD = 2U,
        /// <summary>
        /// Phong Shading (Not yet supported by most implementation)
        /// </summary>
        VXSHADE_PHONG = 3U,
        // VXSHADE_MASK = 3U,
    }

    /// <summary>
    /// Comparison Function
    /// </summary>
    public enum VXCMPFUNC : uint {
        /// <summary>
        /// Always fail the test.
        /// </summary>
        VXCMP_NEVER = 1U,
        /// <summary>
        /// Accept if value if less than current value.
        /// </summary>
        VXCMP_LESS = 2U,
        /// <summary>
        /// Accept if value if equal than current value.
        /// </summary>
        VXCMP_EQUAL = 3U,
        /// <summary>
        /// Accept if value if less or equal than current value.
        /// </summary>
        VXCMP_LESSEQUAL = 4U,
        /// <summary>
        /// Accept if value if greater than current value.
        /// </summary>
        VXCMP_GREATER = 5U,
        /// <summary>
        /// Accept if value if different than current value.
        /// </summary>
        VXCMP_NOTEQUAL = 6U,
        /// <summary>
        /// Accept if value if greater or equal current value.
        /// </summary>
        VXCMP_GREATEREQUAL = 7U,
        /// <summary>
        /// Always accept the test.
        /// </summary>
        VXCMP_ALWAYS = 8U,
        // /// <summary>
        // /// Mask for all possible values.
        // /// </summary>
        // VXCMP_MASK = 0xFU,
    }

    /// <summary>
    /// Mesh lighting options
    /// </summary>
    public enum VXMESH_LITMODE : uint {
        /// <summary>
        /// Lighting use color information store with vertices
        /// </summary>
        VX_PRELITMESH = 0,
        /// <summary>
        /// Lighting is done by renderer using normals and face material information.
        /// </summary>
        VX_LITMESH = 1,
    }

    public enum CK_CAMERA_PROJECTION : uint {
        CK_PERSPECTIVEPROJECTION = 1,
        CK_ORTHOGRAPHICPROJECTION = 2,
    };

    #endregion

}
